document.write("<foot>")
document.write("    <footer class='laptop_view'>")
document.write("        <center>")
document.write("           <div style='padding: 2vw; font-size: 1vw;'>")
document.write("               <table class='center' style='width: 60%;'>")
document.write("                   <tr>")
document.write("                        <td style='text-align: center; width: 25%;'><a href='index.html'>Home</a></td>")
document.write("                        <td style='text-align: center; width: 25%;'><a href='about.html'>About</a></td>")
document.write("                        <td style='text-align: center; width: 25%;'><a href='games.html'>Games</a></td>")
document.write("                        <td style='text-align: center; width: 25%;'><a href='contact.html'>Contact</a></td>")
document.write("                    </tr>")
document.write("                </table>")
document.write("            </div>")
document.write("        </center>")
document.write("        <center>This static website is built with HTML-CSS-javascript<br>Images drawn with Sketch</center>")
document.write("    </footer>")
document.write("    <footer class='mobile_view'>")
document.write("        <center>")
document.write("            <div style='padding: 2vw; font-size: 36px'>")
document.write("                    <a href='index.html' style='margin: 1vw;'>Home</a><br><br>")
document.write("                    <a href='about.html' style='margin: 1vw;'>About</a><br><br>")
document.write("                    <a href='games.html' style='margin: 1vw;'>Games</a><br><br>")
document.write("                    <a href='contact.html' style='margin: 1vw;'>Contact</a><br><br>")
document.write("            </div>")
document.write("        </center>")
document.write("        <center> <div style='font-size: 24px;'>This static website is built with HTML-CSS-javascript<br>Images drawn with Sketch</div></center>")
document.write("    </footer>")
    
document.write("</foot>")